### ISSUE TITLE
No loader or btn disabled indication to show the status the signup data has been submitted

### ISSUE THREAD

**Issue by r-ush** [amanjagdev/stockify#11]

**Comment by GagandeepSingh0115** [comment]
hi, I would like to work on this issue please assign it to me

**Comment by kg-kartik** [comment]
Hi @GagandeepSingh0115 , same needs to be done for all the form pages in which data is being submitted in one or the other way. I am assigning you the issue.
 If you have any doubt, feel free to ping!

**Comment by GagandeepSingh0115** [comment]
Sry sir , I'm kinda busy some where ,
So i will not be able complete it.

**Comment by Krishna-Sivakumar** [comment]
I'll try doing this @kg-kartik 
can you give me more details? Is there a discord I can join?

**Comment by kg-kartik** [comment]
> I'll try doing this @kg-kartik
> can you give me more details? Is there a discord I can join?

You just need to have a loader in submit button of form pages as long as the data is being submitted.
Like as long as the request is being hit at the api endpoint show that loader, and when it is done requesting the particular endpoint, then it would take you to the next page or give you the response back.
So **, Just show the loader as long as the request is being processed.**

**Comment by rajatRS** [comment]
@kg-kartik Would you please assign me to add the loader in the submit button :)

**Comment by Krishna-Sivakumar** [comment]
Got you. I'll work on this @kg-kartik

**Comment by kg-kartik** [comment]
@Krishna-Sivakumar @rajatRS ,
You both can raise the PR tho.

**Comment by GagandeepSingh0115** [comment]
Hi @kg-kartik can i do the same?

**Comment by kg-kartik** [comment]
> Hi @kg-kartik can i do the same?

Yes sure

**Comment by GagandeepSingh0115** [comment]
ok great

**Comment by sanchitgupta001** [comment]
https://github.com/amanjagdev/stockify/pull/33
Pull request for the fix.
