### ISSUE TITLE
React directory structure can be updated with segregated css files

### ISSUE THREAD

**Issue by rajayush012** [amanjagdev/stockify#14]
In the client folder (React), each component or page can have it's own directory where lives a .jsx file and .css/.scss file. This will make the project structure more readable, and UI modification can be done easily.

For e.g. say Sign-up page.
Current dircectory structure:
client -> src -> pages -> SignUp.js

Proposed directory structure : 
client -> src -> pages -> SignUp -> signup.component.js /.jsx
client -> src -> pages -> SignUp -> signup.styles.css / .scss

client -> src -> components -> <component-name> -> <component-name>.component.js/.jsx
client -> src -> components -> <component-name> -> <component-name>.styles.css/.scss

We can, therefore, have stylesheets for every single component instead of a single index.css

**Comment by Kanadets** [comment]
Hey! I'll do this :)

**Comment by amanjagdev** [comment]
@rajayush012  There is no need of it
