### ISSUE TITLE
Add GitHub Repo Links to the site

### ISSUE THREAD

**Issue by amanjagdev** [amanjagdev/stockify#6]
A "Star us on GitHub" and "Fork us on Github" button need to be added in the web application without disturbing the styling and working of the application.
It would help newcomers to contribute to the project by directly staring and forking the repo.

**Comment by wskinner74** [comment]
Hey there, I'd love to help with this. Do you have any preference for where you'd like the buttons located on the web app? I assume the footer would help keep it clean and minimize disturbing the styling of the main interface.

**Comment by shraddhahinge** [comment]
I can add it below your About Us section and I would love to add it with the GitHub logo and with the status/sentence like 👉 " A small contribution to us would be always appreciable" and below this sentence, I can add the 2 buttons of "Star us on GitHub" and "Fork us on Github". If you like my idea let me know, I would love to contribute😉

**Comment by amanjagdev** [comment]
@shraddhahinge I would like it to be visible to the users even without scrolling.
@wskinner74 Placing them in the footer would also result in the same problem as mentioned above unless the footer is made sticky.

If anyone of you can make the footer sticky and add them there that would be a good option
Feel free to mention iff you have any other idea that can suits the requirement

**Comment by jainanuj261** [comment]
Hello @amanjagdev, I'm seeing that your website is on Heroku, that's nice but I want to tell you that when I visit your webpage I saw that every button you have added, it looks like a static or not like a button because when we hover it on it should change to hand arrow but actually its not.

**Comment by wskinner74** [comment]
@amanjagdev Yeah, I can work on making the footer sticky if you think that would look okay.

**Comment by wskinner74** [comment]
@jainanuj261 looks like this is referenced in issue #13

**Comment by jainanuj261** [comment]
Hi, @amanjagdev I have fixed the issues. check it that

**Comment by mohammed-ijas** [comment]
Hi, @amanjagdev  I have fixed issue. Added floating buttons.
