### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by amanjagdev** [amanjagdev/stockify#8]
The documentation doesn't provide much detail about the project and there is not enough information.
Documentation must cover topics :
- Project Description
- Technologies used
- Getting Started: Local installation guide
- Contributing guide

**Comment by Aarush-Goyal** [comment]
Can I work on It?

**Comment by amanjagdev** [comment]
> Can I work on It?

Yes, sure I hope you understand what is needed to be added in the documentation. Please do the following and make a pull request for the same.
Feel free to ping if you need any more information on this.
I am assigning you to this issue.

**Comment by Aarush-Goyal** [comment]
@amanjagdev Thanks!

**Comment by navya252001** [comment]
I have also started working on it
Sorry I did not know that we have to ask for permission

**Comment by kg-kartik** [comment]
> I have also started working on it
> Sorry I did not know that we have to ask for permission

Sorry, but you can work on some another issue, we will be opening more issues in a while!

**Comment by Aarush-Goyal** [comment]
@amanjagdev just wanted to know what technologies are you working with also what features have been successfully implemented till now because the live website is looking more like a static website and the authentication is also not working properly I am not able to sign up or sign in

**Comment by amanjagdev** [comment]
@Aarush-Goyal  This is made using MERN Stack and all the features have been implemented and as this was not maintained for a long time there might be some bug in the authentication.

**Comment by Aarush-Goyal** [comment]
`$ yarn start
yarn run v1.22.10
$ node server.js
C:\Users\goyal\Open-Source\stockify\node_modules\mongoose\lib\connection.js:651
    throw new MongooseError('The `uri` parameter to `openUri()` must be a ' +
    ^

MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first 
parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
    at NativeConnection.Connection.openUri (C:\Users\goyal\Open-Source\stockify\node_modules\mongoose\lib\connection.js:651:11)
    at C:\Users\goyal\Open-Source\stockify\node_modules\mongoose\lib\index.js:341:10
    at promiseOrCallback (C:\Users\goyal\Open-Source\stockify\node_modules\mongoose\lib\helpers\promiseOrCallback.js:9:12)
    at Mongoose.connect (C:\Users\goyal\Open-Source\stockify\node_modules\mongoose\lib\index.js:340:10)  
    at Object.<anonymous> (C:\Users\goyal\Open-Source\stockify\server.js:17:10)
    at Module._compile (internal/modules/cjs/loader.js:1236:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1257:10)
    at Module.load (internal/modules/cjs/loader.js:1085:32)
    at Function.Module._load (internal/modules/cjs/loader.js:950:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**I am facing this problem while installing it locally**

**Comment by kg-kartik** [comment]
> @amanjagdev `$ yarn start yarn run v1.22.10 $ node server.js C:\Users\goyal\Open-Source\stockify\node_modules\mongoose\lib\connection.js:651 throw new MongooseError('The `uri`parameter to`openUri()` must be a ' +
> ^
> 
> MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first
> parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
> at NativeConnection.Connection.openUri (C:\Users\goyal\Open-Source\stockify\node_modules\mongoose\lib\connection.js:651:11)
> at C:\Users\goyal\Open-Source\stockify\node_modules\mongoose\lib\index.js:341:10
> at promiseOrCallback (C:\Users\goyal\Open-Source\stockify\node_modules\mongoose\lib\helpers\promiseOrCallback.js:9:12)
> at Mongoose.connect (C:\Users\goyal\Open-Source\stockify\node_modules\mongoose\lib\index.js:340:10)
> at Object. (C:\Users\goyal\Open-Source\stockify\server.js:17:10)
> at Module._compile (internal/modules/cjs/loader.js:1236:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:1257:10)
> at Module.load (internal/modules/cjs/loader.js:1085:32)
> at Function.Module._load (internal/modules/cjs/loader.js:950:14)
> at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
> at internal/main/run_main_module.js:17:47
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`
> 
> **I am facing this problem while installing it locally**

You need to get your own Mongo uri from google cloud atlas platform for the mongo database and make a new file .env and then define it there as DATABASE = "your mongo uri here"

**Comment by Aarush-Goyal** [comment]
@amanjagdev I guess it's too early for me to contribute to open source. Pls assign this issue to someone else

**Comment by amanjagdev** [comment]
@Aarush-Goyal  It's just that ... Maybe you had a hard time understanding this project but its never too early to contribute to open source. Try your hands on other issues :)
Anyways, I will assign this issue to someone else... Thank you for trying your best.

**Comment by shriyaMadan** [comment]
Hey! May I work on the documentation?

**Comment by amanjagdev** [comment]
@shriyaMadan  Ya sure... I will be assigning this issue to you.

**Comment by shriyaMadan** [comment]
@amanjagdev Done! Please review it and tell any changes that are required.

**Comment by navya252001** [comment]
Sir please help me in HACKTOBER FEST 2020
We will honor all valid pull requests prior to this change, and as of October 3, 2020 at 12:00:00 UTC – and October 3 in all time zones – pull requests will only count toward earning a T-shirt or planting a tree if they are submitted in a repository classified with the ‘hacktoberfest’ topic. The pull requests will also need to be merged, approved by a maintainer, or labeled as ‘hacktoberfest-accepted’ in order to qualify. The deadline for completions, merging, labeling, and approving is November 1.
Latest guidelines issued by the organizers
I sincerely hope you will help me
YOU HAVE CLOSED YOUR ISSUE IN ANIVERSE REPO. PLEASE LOOK INTO THIS MATTER

**Comment by navya252001** [comment]
https://hacktoberfest.digitalocean.com/hacktoberfest-update
I am attaching the link too for your convinience
I contributed to your readme in aniverse

**Comment by amanjagdev** [comment]
Issue has been fixed by PR #27
